default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1g9vndh8a442x62d5q0celx0kxvtd38jm5x5saawrvzhzg0hwyvusahkskm"]

[secrets]
GITHUB_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUGFIT1NONWh0MFpqQjVzSlJDMEIwb04yY0JIWjNMdW1VTzhFVjFJTVVZCjVtWkN3WDFBL3lZN00ySDk2QXRsZENPa1dHYW03ZEdXSDFYRGQwNTJUV28KLT4gST5HXmswa0ktZ3JlYXNlIDQtXS0jICllNzIgQXYKOFhGZkhoQUVybkpLWkQxRUFRN05zaEM5cTE1UnlHSDdWSitZbW84TWxIZXU4NHRpZEZBZll4YkI5WkVBNEdHQwpJa3FpcHAxZU11Tm5kRFNIenVVdUx4Yk1RU2ZuTmJFMkZjREF3dFo0S0hYQUpDNE1xdHppT2NIRmJxNVlYWWMrClh3Ci0tLSBtUUUxSFVjMGtoL3RmVmlkMXk5cVNVOUpVMzFZMDV4dVZ5YktXRFBibVBnCiWb71HPWguY9UwNuZozlGX+HD8sPlWwKZom1fRMLwaMwTJV6DGnbSD8SK6FNkSyLutunWgmGdVOLVuVzaMYHaiTONuOCGp43AtR1Dosrnq1jtd7e98kZESq0UaHloi7lPXPI5rGQHbTJ4rXTNI8AOqH72c+SPLrNTQ5FoTa" }
