default_provider = "age-se"

[providers.age-se]
type = "age"
recipients = ["age1se1q0q39jsxv5zje7zqtjvnz4r6y3305lqkka5t9frtfk49lz6g4vdhvqhfwsk"]
key_file = "~/.config/fnox/age-se.txt"

[secrets]
GITHUB_TOKEN= { provider = "age-se", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHYxT3ViUSBBcUpHK1hhcVlpcC9DdmRqUzFKWTVDZmhxZWROVTByUUhsdm9QRGZ1NU5XSgpTWXFvcWpHVnpjV3J3UVBkQzczZk9BdnFNTUtFOC9wZkNjeWxubW5xR0JVCi0+IDdgQWVHTlhiLWdyZWFzZSA0IF5GUyB8Mn1feyQKcXlYRzJ2UjIKLS0tIHV4NjVRNUxOenV2Ym40NUV4MVBLay82aHhCK1FSMVJFREQ0aEl1M1ZoMkUKLWU8OCwC8cSjXUK/A4jAF8UWYN+Sl4fk4cvzwB8lhHPgvztUMW96baL61n1IWpP6lrSt4zOOwN8E1VMLRUQHrLqXj7aRZd4P0ibdsDilAqy9tqSkeBISx0are5bj2c9Y99M0CPILzPnRLvOAEN75/PtEFIH3g87ddf5pj9E=" }
